spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
jwt:
  token:
    secretkey: 22fc6ee3ec649fdd81e2230b

